GET http://localhost:3001/api/clases

##################

GET http://localhost:3001/api/clases/1

###############################
POST http://localhost:3001/api/clases
Content-Type: application/json 

{
    "id":9,
    "nombre":"clase de programacion"
}