GET http://localhost:3001/api/users

##################

GET http://localhost:3001/api/users/2

###############################
POST http://localhost:3001/api/users
Content-Type: application/json 

  {
      "idUsuario":55,
      "nombre":"Mati",
      "apellido":"Dudev"    }